#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=ExampleJob
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=24:00:00
#SBATCH --mem=32000M
#SBATCH --output=outputs/slurm_output_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

# Your job starts in the directory where you call sbatch
cd $HOME/causal_PVR_MNIST/

source activate interchange-interventions-training

srun python3 -u causal_PVR_MNIST.py --n_epoch 15


